kumuluzee:
  cors-filter:
    annotations:
      catalog:
        allow-origin: "*"
        allow-subdomains: false
  name: catalog-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://etcd-client:2379
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 1000
    etcd:
      hosts: http://etcd-client:2379
aws-config:
  dynamo-region: us-east-1
  table-name: ProductCatalog
  cognito-issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw


