kumuluzee:
  cors-filter:
    servlet:
      enabled: true
      allow-generic-http-requests: true
      allow-origin: "*"
      allow-subdomains: true
      supported-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
      supported-headers: "*"
      exposed-headers: ""
      supports-credentials: true
      max-age: 3600
  name: catalog-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://etcd-client:2379
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 1000
    etcd:
      hosts: http://etcd-client:2379
aws-config:
  dynamo-region: us-east-1
  table-name: ProductCatalog
  cognito-issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw


