kumuluzee:
  cors-filter:
    servlet:
      enabled: true
      allow-generic-http-requests: true
      allow-origin: "*"
      allow-subdomains: true
      supported-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
      supported-headers: "*"
      exposed-headers: ""
      supports-credentials: true
      max-age: 3600
  openapi-mp:
    extension: true
    version: "3.0.1"
    servlet:
      mapping: /products/api-specs/*
    ui:
      enabled: true
      mapping: /products/api-specs/ui
      specification-server: http://20.231.233.217/products/api-specs
      server-auto-config:
        enabled: true
        original-uri-check: false
  logs:
    config-file:
        '<?xml version="1.0" encoding="UTF-8"?>
         <Configuration name="tutorial-logging">
           <Appenders>
             <!-- Existing Console Appender -->
             <Socket name="logstash" protocol="udp" host="10.0.202.212" port="5043">
               <JsonLayout compact="true" eventEol="true" />
             </Socket>
           </Appenders>
           <Loggers>
             <!-- Default logger -->
             <Root level="trace">
               <AppenderRef ref="console"/>
               <AppenderRef ref="logstash"/>
             </Root>
           </Loggers>
         </Configuration>'
  name: catalog-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://etcd-client:2379
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 90000
    etcd:
      hosts: http://etcd-client:2379
  health:
    servlet:
      mapping: /products/health
      enabled: true
#    logs:
#      enabled: true
#      type: both
#      level: FINE
#      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 100000000
      etcd-health-check:
        connection-url: http://etcd-client:2379/health
      http-health-check:
        connection-url: https://github.com/metodija747/MicroserviceMasterProductCatalog.git
  metrics:
    servlet:
      enabled: true
      mapping: /products/metrics
#    logstash:
#      enabled: true
#      address: udp://logstash-logstash:5043
#      port: 5043
#      period-s: 60
  jwt-auth:
    jwks-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw/.well-known/jwks.json
    issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw
#  opentracing:
#    jaeger:
#      service-name: catalog-service
##      agent-host: localhost
##      agent-port: 5775
##      endpoint: http://localhost:14268/api/traces
#      agent-host: simplest-agent.observability
#      agent-port: 5775
#      reporter:
#        log-spans: true
#        max-queue-size: 10000
#        flush-interval: 1000
#        tags: key1=val1, key2=val2
#      sampler:
#        type: const
#        param: 1
#      propagation: JAEGER
#      traceid-128bit: true
aws-config:
  dynamo-region: us-east-1
  table-name: ProductCatalog
  cognito-issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw
