apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  initContainers:
    - name: sysctl-init
      image: busybox
      command: ["sysctl", "-w", "vm.max_map_count=262144"]
      securityContext:
        privileged: true
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
      ports:
        - containerPort: 9200
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
      env:  # Add this section to set environment variables
        - name: "discovery.type"
          value: "single-node"

