# etcd-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-client   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-client   
  template:
    metadata:
      labels:
        app: etcd-client   
    spec:
      containers:
        - name: etcd-client   
          image: quay.io/coreos/etcd:v3.3.15
          command:
            - /usr/local/bin/etcd
            - --advertise-client-urls=http://etcd-client:2379  
            - --listen-client-urls=http://0.0.0.0:2379
          ports:
            - containerPort: 2379
