apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      tcp {
        port => 5043
      }
    }
    output {
      loki {
        url => "http://loki-service:3100/loki/api/v1/push"
        batch_send_count => 5
        batch_event_count => 5
      }
    }
