apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      tcp {
        port => 5043
        codec => 'json_lines'
      }
    }

    output {
      elasticsearch {
        cloud_id => "74cff50e1a9f4277ab2697af5d06fa7d:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQ0NThhMDcyOWU1MTU0YmI3YjQ2ZDU4ZmE5OGZlOTNlMSQ4Zjg4ODk3ZmMxMDU0M2UzOWFiYWYyYjQxM2M0MzBiNg=="
        cloud_auth => "elastic:MUWY0TxnaHpDKAJLWVnio4A2"
      }
    }
