apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      tcp {
        port => 5043
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
