apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    input {
      udp {
        port => 5043
      }
    }
    output {
      elasticsearch {
        hosts => ["https://mastermicroservice-4c000c.es.us-central1.gcp.cloud.es.io:9200"]
        user => "elastic"
        password => "JIyTL9ptLZ3fWXAAqbJHiXnt"
      }
    }
