apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    input {
      tcp {
        port => 5000
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
      }
    }
