apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ingress-basic
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'products-microservice'
        metrics_path: '/products/metrics'
        static_configs:
        - targets: ['20.231.233.217:80']
          labels:
            group: 'product-metrics'
